require 'open3'

# Pagefind search indexing for local builds.
#
# The Search page (/blog/search/) loads /pagefind/pagefind-ui.js, which is
# generated by running `npx pagefind --site _site` AFTER jekyll writes the
# site. GitHub Actions already does this as a separate workflow step, so
# this hook only fills the gap for local `jekyll build` / `jekyll serve`
# (including --watch, where each regeneration would otherwise wipe
# _site/pagefind because Jekyll cleans the destination on every build).
#
# Skipped when JEKYLL_ENV=production (CI) or when npx is unavailable.
Jekyll::Hooks.register :site, :post_write do |site|
  next if ENV['JEKYLL_ENV'] == 'production'

  begin
    out, err, status = Open3.capture3('npx', '--yes', 'pagefind', '--site', site.dest)
  rescue Errno::ENOENT
    Jekyll.logger.warn 'Pagefind:', 'npx not found - skipping search index (install Node.js to enable local search)'
    next
  end

  if status.success?
    Jekyll.logger.info 'Pagefind:', "search index written to #{File.join(site.dest, 'pagefind')}"
  else
    Jekyll.logger.warn 'Pagefind:', "indexing failed - search unavailable locally\n#{err}"
  end
end
