// Markdown blog renderer.
// - Reads posts.json (generated by .github/workflows/blog-index.yml)
// - List view at /blog/, reader view at /blog/<slug>/ (RESTful), tag-filtered at /blog/?tag=<tag>
// - Back-compat: legacy /blog/?p=<slug> URLs still work
// - Supports GFM, fenced code (highlight.js), KaTeX math, Obsidian [[wikilinks]] and ![[image]] embeds
// - Renders inline #hashtags as clickable tag links

const BLOG_BASE = "/blog/";
const POSTS_JSON = BLOG_BASE + "posts.json";
const POSTS_DIR = BLOG_BASE + "posts";

const listView = document.getElementById("list-view");
const readerView = document.getElementById("reader-view");
const postList = document.getElementById("post-list");
const postContent = document.getElementById("post-content");
const postCount = document.getElementById("post-count");
const tagNavList = document.getElementById("tag-nav-list");
const tagNavListReader = document.getElementById("tag-nav-list-reader");

function fmtDate(s) {
    if (!s) return "";
    const d = new Date(s);
    if (isNaN(d)) return s;
    return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

function queryParam(name) {
    const m = location.search.match(new RegExp(`[?&]${name}=([^&]+)`));
    return m ? decodeURIComponent(m[1]) : null;
}

function slugFromQuery() {
    if (typeof window.__POST_SLUG__ === "string" && window.__POST_SLUG__) {
        return window.__POST_SLUG__;
    }
    const m = location.pathname.match(/\/blog\/([^/?#]+)\/?$/);
    if (m && m[1] && m[1] !== "posts") return decodeURIComponent(m[1]);
    return queryParam("p");
}

function tagFromQuery() {
    const t = queryParam("tag");
    return t ? t.toLowerCase() : null;
}

function renderTagNav(tags, activeTag, target) {
    if (!target) return;
    const entries = Object.entries(tags || {});
    if (entries.length === 0) {
        target.innerHTML = `<li class="tag-empty">No tags yet</li>`;
        return;
    }
    const total = entries.reduce((s, [, n]) => s + n, 0);
    const items = [`<li class="tag-item${!activeTag ? " active" : ""}"><a href="${BLOG_BASE}">All <span class="tag-count">${total}</span></a></li>`];
    for (const [name, count] of entries) {
        const isActive = activeTag && activeTag === name;
        items.push(`<li class="tag-item${isActive ? " active" : ""}"><a href="${BLOG_BASE}?tag=${encodeURIComponent(name)}">#${escapeHtml(name)} <span class="tag-count">${count}</span></a></li>`);
    }
    target.innerHTML = items.join("");
}

function renderList(posts, activeTag) {
    if (!postList) return;
    const filtered = activeTag
        ? (posts || []).filter((p) => (p.tags || []).some((t) => String(t).toLowerCase() === activeTag))
        : (posts || []);
    if (postCount) {
        const n = filtered.length;
        postCount.textContent = activeTag
            ? `${n} post${n === 1 ? "" : "s"} tagged #${activeTag}`
            : `${n} post${n === 1 ? "" : "s"}`;
    }
    if (filtered.length === 0) {
        postList.innerHTML = activeTag
            ? `<p style="color: var(--text-dim, #888);">No posts tagged <strong>#${escapeHtml(activeTag)}</strong>. <a href="${BLOG_BASE}">Show all</a>.</p>`
            : `<p style="color: var(--text-dim, #888);">New blog. Coming soon.</p>`;
        return;
    }
    const ul = document.createElement("ul");
    ul.className = "blog-list";
    for (const p of filtered) {
        const li = document.createElement("li");
        const tagBits = (p.tags || []).slice(0, 4).map((t) => `<a class="post-tag" href="${BLOG_BASE}?tag=${encodeURIComponent(String(t).toLowerCase())}">#${escapeHtml(t)}</a>`).join(" ");
        li.innerHTML = `
            <span class="blog-date">${fmtDate(p.date)}</span>
            <span class="blog-title">
                <a href="${BLOG_BASE}${encodeURIComponent(p.slug)}/">${escapeHtml(p.title)}</a>
                ${p.excerpt ? `<br><span style="color:var(--text-dim, #888); font-weight:normal; font-size:0.9em;">${escapeHtml(p.excerpt)}</span>` : ""}
                ${tagBits ? `<br><span class="post-tag-row">${tagBits}</span>` : ""}
            </span>
            <span class="blog-read"></span>
        `;
        ul.appendChild(li);
    }
    postList.innerHTML = "";
    postList.appendChild(ul);
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function parseFrontmatter(src) {
    const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
    if (!m) return { data: {}, body: src };
    const data = {};
    for (const line of m[1].split("\n")) {
        const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
        if (!kv) continue;
        let [, k, v] = kv;
        v = v.trim();
        if (v.startsWith("[") && v.endsWith("]")) {
            v = v.slice(1, -1).split(",").map((x) => x.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
        } else if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
            v = v.slice(1, -1);
        }
        data[k] = v;
    }
    return { data, body: src.slice(m[0].length) };
}

function preprocessWikilinks(md, basePath) {
    md = md.replace(/!\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, alt) => {
        const src = target.trim();
        const altText = (alt || src).trim();
        const fullSrc = /^https?:\/\//.test(src) || src.startsWith("/") ? src : `${basePath}/${src}`;
        return `![${altText}](${fullSrc})`;
    });
    md = md.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, display) => {
        const t = target.trim();
        const d = (display || t).trim();
        const slug = t.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
        return `[${d}](${BLOG_BASE}${encodeURIComponent(slug)}/)`;
    });
    return md;
}

// Replace Obsidian-style inline #hashtags with markdown links, leaving
// headings and fenced/inline code untouched.
function preprocessHashtags(md) {
    const out = [];
    let inFence = false;
    for (const line of md.split("\n")) {
        if (/^\s*(```|~~~)/.test(line)) {
            inFence = !inFence;
            out.push(line);
            continue;
        }
        if (inFence || /^\s*#{1,6}\s+/.test(line)) {
            out.push(line);
            continue;
        }
        const parts = line.split(/(`[^`]*`)/);
        for (let i = 0; i < parts.length; i++) {
            if (i % 2 === 1) continue;
            parts[i] = parts[i].replace(
                /(^|[\s(\[{,;:.!?"'>])#([A-Za-z][\w-]*)/g,
                (_, lead, tag) => `${lead}[#${tag}](${BLOG_BASE}?tag=${encodeURIComponent(tag.toLowerCase())})`
            );
        }
        out.push(parts.join(""));
    }
    return out.join("\n");
}

async function renderPost(slug, manifest) {
    const meta = (manifest || []).find((p) => p.slug === slug);
    // meta.path is repo-relative under blog/, e.g. "posts/framework.md".
    const path = meta ? `${BLOG_BASE}${meta.path}` : `${POSTS_DIR}/${slug}/index.md`;
    const basePath = path.replace(/\/[^\/]+$/, "");
    let res;
    try {
        res = await fetch(path);
    } catch (e) {
        postContent.innerHTML = `<p>Could not load post: ${escapeHtml(slug)}</p>`;
        return;
    }
    if (!res.ok) {
        postContent.innerHTML = `<p>Post not found: ${escapeHtml(slug)}</p>`;
        return;
    }
    const raw = await res.text();
    const { data, body } = parseFrontmatter(raw);
    let md = preprocessWikilinks(body, basePath);
    md = preprocessHashtags(md);

    if (window.markedHighlight && window.hljs) {
        marked.use(
            markedHighlight.markedHighlight({
                langPrefix: "hljs language-",
                highlight(code, lang) {
                    const language = window.hljs.getLanguage(lang) ? lang : "plaintext";
                    return window.hljs.highlight(code, { language }).value;
                },
            })
        );
    }
    marked.setOptions({ gfm: true, breaks: false });

    const html = marked.parse(md);
    const title = data.title || meta?.title || slug;
    const date = data.date || meta?.date;
    const tags = data.tags || meta?.tags || [];

    postContent.innerHTML = `
        <header class="post-header">
            <h1>${escapeHtml(title)}</h1>
            <div class="post-meta">
                ${date ? `<span>${fmtDate(date)}</span>` : ""}
                ${(Array.isArray(tags) ? tags : []).map((t) => `<a class="chip" href="${BLOG_BASE}?tag=${encodeURIComponent(String(t).toLowerCase())}">#${escapeHtml(t)}</a>`).join("")}
            </div>
        </header>
        <div class="post-body">${html}</div>
    `;
    document.title = `${title} - Blog`;

    if (window.renderMathInElement) {
        renderMathInElement(postContent, {
            delimiters: [
                { left: "$$", right: "$$", display: true },
                { left: "$", right: "$", display: false },
                { left: "\\(", right: "\\)", display: false },
                { left: "\\[", right: "\\]", display: true },
            ],
            throwOnError: false,
        });
    }
}

async function loadManifest() {
    try {
        const res = await fetch(POSTS_JSON, { cache: "no-cache" });
        if (!res.ok) return { posts: [], tags: {} };
        const data = await res.json();
        const posts = (data.posts || data || []).slice().sort((a, b) => (b.date || "").localeCompare(a.date || ""));
        let tags = data.tags;
        if (!tags) {
            const counts = {};
            for (const p of posts) {
                for (const t of p.tags || []) {
                    const key = String(t).toLowerCase();
                    counts[key] = (counts[key] || 0) + 1;
                }
            }
            tags = Object.fromEntries(Object.entries(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])));
        }
        return { posts, tags };
    } catch {
        return { posts: [], tags: {} };
    }
}

async function route() {
    const { posts, tags } = await loadManifest();
    const slug = slugFromQuery();
    const activeTag = tagFromQuery();
    renderTagNav(tags, activeTag, tagNavList);
    renderTagNav(tags, activeTag, tagNavListReader);
    if (slug) {
        if (listView) listView.style.display = "none";
        if (readerView) readerView.style.display = "block";
        await renderPost(slug, posts);
        window.scrollTo(0, 0);
    } else {
        if (readerView) readerView.style.display = "none";
        if (listView) listView.style.display = "block";
        renderList(posts, activeTag);
    }
}

window.addEventListener("popstate", route);
route();
