#!/usr/bin/env python3
"""Walk blog/posts/, parse frontmatter and inline #hashtags, write blog/posts.json.

Also generates per-post static HTML pages at blog/<slug>/index.html with baked-in
Open Graph + Twitter Card meta tags so shared links (WhatsApp, X, Slack, etc.)
get rich previews. Post body renders client-side via blog.js.

Triggered by the .github/workflows/blog-index.yml workflow on every push that
touches blog/posts/**. Local equivalent: python scripts/build_blog_index.py
"""
from __future__ import annotations

import html
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BLOG_DIR = ROOT / "blog"
POSTS_DIR = BLOG_DIR / "posts"
INDEX_FILE = BLOG_DIR / "posts.json"
LIST_HTML = BLOG_DIR / "index.html"
CNAME_FILE = ROOT / "CNAME"

GENERATED_MARKER = "<!-- generated by build_blog_index.py - do not edit -->"

INLINE_TAG_RE = re.compile(r"(?:^|[\s(\[{,;:.!?\"'>])#([A-Za-z][\w-]*)")
FENCE_RE = re.compile(r"^\s*(```|~~~)")
HEADING_RE = re.compile(r"^\s*#{1,6}\s+")


def parse_frontmatter(text: str) -> tuple[dict, str]:
    m = re.match(r"^---\n([\s\S]*?)\n---\n?", text)
    if not m:
        return {}, text
    data: dict = {}
    for line in m.group(1).splitlines():
        kv = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not kv:
            continue
        k, v = kv.group(1), kv.group(2).strip()
        if v.startswith("[") and v.endswith("]"):
            v = [s.strip().strip("'\"") for s in v[1:-1].split(",") if s.strip()]
        elif (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        data[k] = v
    return data, text[m.end():]


def extract_inline_tags(body: str) -> list[str]:
    tags: list[str] = []
    in_fence = False
    for line in body.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if HEADING_RE.match(line):
            continue
        line_no_code = re.sub(r"`[^`]*`", "", line)
        for m in INLINE_TAG_RE.finditer(line_no_code):
            tag = m.group(1).lower()
            if tag not in tags:
                tags.append(tag)
    return tags


def excerpt_from(body: str, n: int = 240) -> str:
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", body)
    text = re.sub(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]", lambda m: m.group(2) or m.group(1), text)
    text = re.sub(r"`[^`]*`", "", text)
    text = re.sub(r"[#*_>]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:n] + ("..." if len(text) > n else "")


def collect() -> tuple[list[dict], dict[str, int]]:
    if not POSTS_DIR.exists():
        return [], {}
    posts: list[dict] = []
    tag_counts: dict[str, int] = {}
    # Two layouts supported:
    #   posts/<slug>/index.md         (preferred, allows colocated images)
    #   posts/<slug>.md               (also fine)
    for md in sorted(POSTS_DIR.rglob("*.md")):
        rel = md.relative_to(ROOT).as_posix()
        try:
            text = md.read_text(encoding="utf-8")
        except Exception:
            continue
        data, body = parse_frontmatter(text)
        if md.name == "index.md":
            slug = md.parent.name
        else:
            slug = md.stem
        title = data.get("title") or slug.replace("_", " ").replace("-", " ").title()
        date = data.get("date") or ""
        front_tags = data.get("tags") or []
        if isinstance(front_tags, str):
            front_tags = [t.strip() for t in front_tags.split(",") if t.strip()]
        inline_tags = extract_inline_tags(body)
        merged: list[str] = []
        seen: set[str] = set()
        for t in list(front_tags) + inline_tags:
            key = t.lower()
            if key in seen:
                continue
            seen.add(key)
            merged.append(key)
        for t in merged:
            tag_counts[t] = tag_counts.get(t, 0) + 1
        excerpt = data.get("excerpt") or excerpt_from(body)
        image = data.get("image") or ""
        posts.append(
            {
                "slug": slug,
                "title": title,
                "date": str(date),
                "tags": merged,
                "excerpt": excerpt,
                "image": image,
                "path": rel.split("/", 1)[1] if rel.startswith("blog/") else rel,
            }
        )
    posts.sort(key=lambda p: p.get("date", ""), reverse=True)
    return posts, tag_counts


def site_base_url() -> str:
    if CNAME_FILE.exists():
        host = CNAME_FILE.read_text(encoding="utf-8").strip().splitlines()[0].strip()
        if host:
            return f"https://{host}"
    # Fallback: derive from repo dir name (works for user.github.io repos).
    repo_name = ROOT.name
    return f"https://{repo_name}"


def extract_block(html_src: str, tag: str) -> str:
    m = re.search(rf"<{tag}\b[^>]*>[\s\S]*?</{tag}>", html_src, re.IGNORECASE)
    return m.group(0) if m else ""


def rewrite_relative_links(html_src: str) -> str:
    """Rewrite blog/index.html relative paths so they work from blog/<slug>/index.html.

    From blog/index.html, "./X" means blog/X and "../X" means /X.
    From blog/<slug>/index.html, the same logical destinations need rewriting.
    """
    # ../X  -> /X
    html_src = re.sub(r'(href|src)="\.\./', r'\1="/', html_src)
    # ./X (including ./ alone) -> /blog/X
    html_src = re.sub(r'(href|src)="\./', r'\1="/blog/', html_src)
    return html_src


def page_url(base: str, slug: str) -> str:
    return f"{base.rstrip('/')}/blog/{slug}/"


def render_post_html(post: dict, site_base: str, nav_html: str, footer_html: str) -> str:
    title = post.get("title") or post.get("slug") or "Post"
    excerpt = post.get("excerpt") or ""
    slug = post.get("slug") or ""
    date = post.get("date") or ""
    image = post.get("image") or ""
    url = page_url(site_base, slug)

    title_esc = html.escape(title, quote=True)
    excerpt_esc = html.escape(excerpt, quote=True)
    slug_js = slug.replace("\\", "\\\\").replace('"', '\\"')

    og_image_block = ""
    twitter_image_block = ""
    twitter_card = "summary"
    if image:
        # Resolve relative image to absolute URL.
        if image.startswith(("http://", "https://")):
            abs_image = image
        elif image.startswith("/"):
            abs_image = f"{site_base.rstrip('/')}{image}"
        else:
            abs_image = f"{site_base.rstrip('/')}/blog/posts/{image}"
        og_image_block = f'<meta property="og:image" content="{html.escape(abs_image, quote=True)}" />'
        twitter_image_block = f'<meta name="twitter:image" content="{html.escape(abs_image, quote=True)}" />'
        twitter_card = "summary_large_image"

    article_time = ""
    if date:
        article_time = f'<meta property="article:published_time" content="{html.escape(date, quote=True)}" />'

    return f"""{GENERATED_MARKER}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{title_esc} - Blog</title>
        <link rel="canonical" href="{html.escape(url, quote=True)}" />
        <meta name="description" content="{excerpt_esc}" />

        <meta property="og:type" content="article" />
        <meta property="og:title" content="{title_esc}" />
        <meta property="og:description" content="{excerpt_esc}" />
        <meta property="og:url" content="{html.escape(url, quote=True)}" />
        {og_image_block}
        {article_time}

        <meta name="twitter:card" content="{twitter_card}" />
        <meta name="twitter:title" content="{title_esc}" />
        <meta name="twitter:description" content="{excerpt_esc}" />
        {twitter_image_block}

        <link rel="stylesheet" href="/style.css" />
        <link rel="stylesheet" href="/blog/blog.css" />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/highlight.js@11.10.0/styles/atom-one-dark.min.css"
        />
    </head>
    <body>
        {nav_html}

        <main id="reader-view">
            <div class="container">
                <p style="margin: 2rem 0 1rem">
                    <a href="/blog/" class="btn">&larr; All posts</a>
                </p>
                <div class="blog-layout reader-layout">
                    <aside class="tag-sidebar" aria-label="Tags">
                        <h3 class="tag-sidebar-title">Tags</h3>
                        <ul id="tag-nav-list-reader" class="tag-list">
                            <li class="tag-empty">Loading...</li>
                        </ul>
                    </aside>
                    <div class="blog-main">
                        <article id="post-content" class="prose"></article>
                    </div>
                </div>
                <p style="margin: 3rem 0 1rem">
                    <a href="/blog/" class="btn">&larr; All posts</a>
                </p>
            </div>
        </main>

        {footer_html}

        <script>window.__POST_SLUG__ = "{slug_js}";</script>
        <script src="https://cdn.jsdelivr.net/npm/marked@13.0.3/marked.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/marked-highlight@2.1.4/lib/index.umd.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/highlight.js@11.10.0/lib/highlight.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" crossorigin="anonymous"></script>
        <script src="/blog/blog.js"></script>
    </body>
</html>
"""


def clean_stale_post_dirs(current_slugs: set[str]) -> list[str]:
    """Remove blog/<dir>/ that we previously generated but no longer have a post for."""
    removed: list[str] = []
    if not BLOG_DIR.exists():
        return removed
    for child in BLOG_DIR.iterdir():
        if not child.is_dir() or child.name == "posts":
            continue
        idx = child / "index.html"
        if not idx.exists():
            continue
        try:
            head = idx.read_text(encoding="utf-8")[:200]
        except Exception:
            continue
        if GENERATED_MARKER not in head:
            continue
        if child.name in current_slugs:
            continue
        shutil.rmtree(child)
        removed.append(child.name)
    return removed


def write_post_pages(posts: list[dict]) -> tuple[int, list[str]]:
    if not LIST_HTML.exists():
        print(f"Warning: {LIST_HTML} not found; skipping per-post HTML generation.")
        return 0, []
    list_src = LIST_HTML.read_text(encoding="utf-8")
    nav_html = rewrite_relative_links(extract_block(list_src, "nav"))
    footer_html = rewrite_relative_links(extract_block(list_src, "footer"))
    base = site_base_url()
    current_slugs = {p["slug"] for p in posts}
    removed = clean_stale_post_dirs(current_slugs)
    written = 0
    for post in posts:
        slug = post["slug"]
        out_dir = BLOG_DIR / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / "index.html"
        html_src = render_post_html(post, base, nav_html, footer_html)
        out_file.write_text(html_src, encoding="utf-8")
        written += 1
    return written, removed


def main() -> None:
    posts, tag_counts = collect()
    ordered = dict(sorted(tag_counts.items(), key=lambda kv: (-kv[1], kv[0])))
    INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    INDEX_FILE.write_text(
        json.dumps({"posts": posts, "tags": ordered}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    written, removed = write_post_pages(posts)
    print(f"Wrote {len(posts)} posts and {len(ordered)} tags to {INDEX_FILE.relative_to(ROOT)}")
    print(f"Generated {written} per-post HTML pages; removed {len(removed)} stale: {removed or '-'}")


if __name__ == "__main__":
    main()
